PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE users (   id INTEGER PRIMARY KEY AUTOINCREMENT,   telegram_id INTEGER NOT NULL UNIQUE,   username TEXT,   first_name TEXT,   phone TEXT,   created_at TEXT DEFAULT CURRENT_TIMESTAMP,   updated_at TEXT DEFAULT CURRENT_TIMESTAMP );
INSERT INTO "users" ("id","telegram_id","username","first_name","phone","created_at","updated_at") VALUES(1,7061635812,NULL,'Иван','+79279677775','2026-07-13 13:13:59','2026-07-13 13:13:59');
CREATE TABLE services (    id INTEGER PRIMARY KEY AUTOINCREMENT,    code TEXT NOT NULL UNIQUE,    name TEXT NOT NULL,    duration_minutes INTEGER NOT NULL DEFAULT 60,    active INTEGER NOT NULL DEFAULT 1,    sort_order INTEGER NOT NULL DEFAULT 0 );
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(1,'cleaning','Чистка лица',60,1,1);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(2,'massage','Массаж',60,1,2);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(3,'mesotherapy','Мезотерапия',60,1,3);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(4,'peeling','Пилинг',60,1,4);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(5,'masks','Маски',60,1,5);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(6,'other','Другое',60,1,6);
CREATE TABLE cities (    id INTEGER PRIMARY KEY AUTOINCREMENT,    code TEXT NOT NULL UNIQUE,    name TEXT NOT NULL,    calendar_id TEXT,    active INTEGER NOT NULL DEFAULT 1 );
INSERT INTO "cities" ("id","code","name","calendar_id","active") VALUES(1,'moscow','Москва',NULL,1);
INSERT INTO "cities" ("id","code","name","calendar_id","active") VALUES(2,'tula','Тула',NULL,1);
CREATE TABLE bookings (    id TEXT PRIMARY KEY,    user_id INTEGER NOT NULL,    service_id INTEGER NOT NULL,    city_id INTEGER NOT NULL,    booking_date TEXT NOT NULL,    start_time TEXT NOT NULL,    end_time TEXT NOT NULL,    status TEXT NOT NULL DEFAULT 'confirmed',    calendar_event_id TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP,    updated_at TEXT DEFAULT CURRENT_TIMESTAMP );
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at") VALUES(NULL,1,2,1,'2026-07-21','16:00','17:00','confirmed',NULL,'2026-07-13 13:14:00','2026-07-13 13:14:00');
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at") VALUES(NULL,1,2,1,'2026-08-02','11:00','12:00','confirmed',NULL,'2026-07-13 13:19:17','2026-07-13 13:19:17');
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at") VALUES(NULL,1,2,1,'2026-07-24','18:00','19:00','confirmed',NULL,'2026-07-13 14:29:45','2026-07-13 14:29:45');
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at") VALUES(NULL,1,2,1,'2026-07-24','16:00','17:00','confirmed','a4u6n25elnrt8ua6206uj4ka2o@google.com','2026-07-13 14:44:44','2026-07-13 14:44:44');
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at") VALUES(NULL,1,4,2,'2026-07-16','13:00','14:00','confirmed','l7tggu2ukrhv59q31u2tqdsbrg@google.com','2026-07-13 14:45:53','2026-07-13 14:45:53');
CREATE TABLE closed_dates (    id INTEGER PRIMARY KEY AUTOINCREMENT,    city_id INTEGER NOT NULL,    date TEXT NOT NULL,    reason TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP,    UNIQUE(city_id, date) );
CREATE TABLE reminders (    id INTEGER PRIMARY KEY AUTOINCREMENT,    booking_id TEXT NOT NULL,    type TEXT NOT NULL,    send_at TEXT NOT NULL,    sent INTEGER DEFAULT 0,    sent_at TEXT );
CREATE TABLE booking_logs (    id INTEGER PRIMARY KEY AUTOINCREMENT,    booking_id TEXT NOT NULL,    action TEXT NOT NULL,    details TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP );
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('services',6);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('cities',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('users',1);
