PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE users (   id INTEGER PRIMARY KEY AUTOINCREMENT,   telegram_id INTEGER NOT NULL UNIQUE,   username TEXT,   first_name TEXT,   phone TEXT,   created_at TEXT DEFAULT CURRENT_TIMESTAMP,   updated_at TEXT DEFAULT CURRENT_TIMESTAMP );
INSERT INTO "users" ("id","telegram_id","username","first_name","phone","created_at","updated_at") VALUES(2,7061635812,NULL,'Иван','+79279677775','2026-07-14 08:18:09','2026-07-14 08:18:09');
CREATE TABLE services (    id INTEGER PRIMARY KEY AUTOINCREMENT,    code TEXT NOT NULL UNIQUE,    name TEXT NOT NULL,    duration_minutes INTEGER NOT NULL DEFAULT 60,    active INTEGER NOT NULL DEFAULT 1,    sort_order INTEGER NOT NULL DEFAULT 0 );
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(1,'cleaning','Чистка лица',60,1,1);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(2,'massage','Массаж',60,1,2);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(3,'mesotherapy','Мезотерапия',60,1,3);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(4,'peeling','Пилинг',60,1,4);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(5,'masks','Маски',60,1,5);
INSERT INTO "services" ("id","code","name","duration_minutes","active","sort_order") VALUES(6,'other','Другое',60,1,6);
CREATE TABLE cities (    id INTEGER PRIMARY KEY AUTOINCREMENT,    code TEXT NOT NULL UNIQUE,    name TEXT NOT NULL,    calendar_id TEXT,    active INTEGER NOT NULL DEFAULT 1 );
INSERT INTO "cities" ("id","code","name","calendar_id","active") VALUES(1,'moscow','Москва',NULL,1);
INSERT INTO "cities" ("id","code","name","calendar_id","active") VALUES(2,'tula','Тула',NULL,1);
CREATE TABLE bookings (    id TEXT PRIMARY KEY,    user_id INTEGER NOT NULL,    service_id INTEGER NOT NULL,    city_id INTEGER NOT NULL,    booking_date TEXT NOT NULL,    start_time TEXT NOT NULL,    end_time TEXT NOT NULL,    status TEXT NOT NULL DEFAULT 'confirmed',    calendar_event_id TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP,    updated_at TEXT DEFAULT CURRENT_TIMESTAMP , reminder_sent INTEGER NOT NULL DEFAULT 0);
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at","reminder_sent") VALUES('fd13a0c6-86f8-44f2-800a-020e738cc144',2,2,1,'2026-07-24','16:00','17:00','cancelled','kvhkv163s9d29jc8ai3dssag34@google.com','2026-07-14 08:18:09','2026-07-14 08:18:28',0);
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at","reminder_sent") VALUES('f5a46907-2d48-4955-bb53-76fb6e221d51',2,2,1,'2026-07-19','10:00','11:00','cancelled','kirvqro0157ats9lj0a8rd25as@google.com','2026-07-14 10:18:16','2026-07-14 10:44:24',0);
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at","reminder_sent") VALUES('fb04e42e-7ab4-4b40-a0d7-dbc28afd035d',2,2,2,'2026-07-15','12:00','13:00','confirmed','nvrc50scdt9o2r0q1h2anl97kg@google.com','2026-07-14 13:50:42','2026-07-14 13:50:42',1);
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at","reminder_sent") VALUES('2759fa01-3e60-4172-b1ed-714049251fc6',2,3,1,'2026-07-22','10:00','11:00','cancelled','qm3hrp0bc5ap64mtfc1sdcbff8@google.com','2026-07-14 14:43:11','2026-07-14 14:44:47',0);
INSERT INTO "bookings" ("id","user_id","service_id","city_id","booking_date","start_time","end_time","status","calendar_event_id","created_at","updated_at","reminder_sent") VALUES('56ef7898-f43e-435c-9ac1-80d6f0e8dfb8',2,6,2,'2026-07-23','15:00','16:00','cancelled','8d64fm64v2rgq1ra33q1nc9dno@google.com','2026-07-14 14:43:56','2026-07-14 14:44:36',0);
CREATE TABLE closed_dates (    id INTEGER PRIMARY KEY AUTOINCREMENT,    city_id INTEGER NOT NULL,    date TEXT NOT NULL,    reason TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP,    UNIQUE(city_id, date) );
CREATE TABLE reminders (    id INTEGER PRIMARY KEY AUTOINCREMENT,    booking_id TEXT NOT NULL,    type TEXT NOT NULL,    send_at TEXT NOT NULL,    sent INTEGER DEFAULT 0,    sent_at TEXT );
CREATE TABLE booking_logs (    id INTEGER PRIMARY KEY AUTOINCREMENT,    booking_id TEXT NOT NULL,    action TEXT NOT NULL,    details TEXT,    created_at TEXT DEFAULT CURRENT_TIMESTAMP );
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('services',6);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('cities',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('users',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('closed_dates',1);
